#!/bin/bash

dir0="../instances"
dir_solutions=$(date +%Y-%m-%d_%H:%M:%S)
mkdir "../solutions/"$dir_solutions

time_limit=3600

start_instance="0"
files=()
time_limit=3600

cont=0
for file in $dir0/*.txt
do
	files[$cont]="$file"
	((cont++))	
done

readarray -t sorted < <(printf '%s\0' "${files[@]}" | sort -z | xargs -0n1)

Relaxation
for file in ${sorted[@]}
do
	substr=$(echo $file | rev | cut -d'/' -f 1 | rev)
	substr=${substr//".txt"/}

	curr_instance=$substr
	if [[ "$curr_instance" > "$start_instance" ]];
	then
		echo "* "$curr_instance
		# Compact
		./bin/stop --solution-dir $dir_solutions --instance $file --solve-relaxed --vehicle-sequencing-model --symmetry-breaking
		./bin/stop --solution-dir $dir_solutions --instance $file --solve-relaxed --vehicle-sequencing-model --symmetry-breaking --reformulate
		./bin/stop --solution-dir $dir_solutions --instance $file --solve-relaxed --vehicle-slots-model --symmetry-breaking
		./bin/stop --solution-dir $dir_solutions --instance $file --solve-relaxed --vehicle-slots-model --symmetry-breaking --reformulate

		# Cut and branch
		./bin/stop --solution-dir $dir_solutions --instance $file --solve-relaxed --vehicle-sequencing-model --symmetry-breaking --CCCs
		./bin/stop --solution-dir $dir_solutions --instance $file --solve-relaxed --vehicle-sequencing-model --symmetry-breaking --reformulate --CCCs
		./bin/stop --solution-dir $dir_solutions --instance $file --solve-relaxed --vehicle-slots-model --symmetry-breaking --CCCs
		./bin/stop --solution-dir $dir_solutions --instance $file --solve-relaxed --vehicle-slots-model --symmetry-breaking --reformulate --CCCs
	fi
done

# # Exact and Kernel Search
# for file in ${sorted[@]}
# do
# 	substr=$(echo $file | rev | cut -d'/' -f 1 | rev)
# 	substr=${substr//".txt"/}

# 	curr_instance=$substr
# 	if [[ "$curr_instance" > "$start_instance" ]];
# 	then
# 		echo "* "$curr_instance
# 		# Compact 
# 		# ./bin/stop --solution-dir $dir_solutions --compact --baseline --warm-start --time-limit $time_limit --instance $file --num-vehicles $num_vehicles --uncertainty-budget $uncertainty_budget --service-time-deviation $service_time_deviation
# 		# ./bin/stop --solution-dir $dir_solutions --compact --capacity-based --warm-start --time-limit $time_limit --instance $file --num-vehicles $num_vehicles --uncertainty-budget $uncertainty_budget --service-time-deviation $service_time_deviation
		
# 		# Kernel Search
# 		# # ./bin/stop --solution-dir $dir_solutions --kernel-search --baseline --instance $file --num-vehicles $num_vehicles --uncertainty-budget $uncertainty_budget --service-time-deviation $service_time_deviation --ks-max-size-bucket 5 --ks-min-time-limit 19 --ks-max-time-limit 84 --ks-decay-factor 0.96 --ks-feasibility-emphasis 1
# 		# ./bin/stop --solution-dir $dir_solutions --kernel-search --capacity-based --instance $file --num-vehicles $num_vehicles --uncertainty-budget $uncertainty_budget --service-time-deviation $service_time_deviation --ks-max-size-bucket 5 --ks-min-time-limit 25 --ks-max-time-limit 72 --ks-decay-factor 0.86 --ks-feasibility-emphasis 0	
# 	fi
# done